msm8916-mainline/linux

arch/arm64/boot/dts/qcom/Makefile, arch/arm64/boot/dts/qcom/msm8916-wileyfox-crackling.dts
Add a device tree for crackling with initial support for:
- SDHCI (internal and external storage)
- USB Device Mode
- UART
- Regulators
=> arm64: dts: qcom: Add device tree for Wileyfox Swift

arch/arm64/boot/dts/qcom/msm8916-longcheer-l8150.dts
Synaptics touchscreen uses rmi4 protocol over i2c bus
- Touchscreen works
- Powered by fixed regulator
=> arm64: dts: msm8916-longcheer-l8150: Add Synaptics touchscreen support

arch/arm64/boot/dts/qcom/msm8916-longcheer-l8150.dts
- All outputs (Speaker, Earpiece, Headphones) works.
=> arm64: dts: msm8916-longcheer-l8150: Sound output works

arch/arm64/boot/dts/qcom/msm8916-longcheer-l8150.dts, drivers/iio/light/ltr501.c
- Reading proximity works only two times after driver load
- Reading light intensity doesn't work
=> L8150: ltr559 support

arch/arm64/boot/dts/qcom/apq8016-samsung-gt510wifi.dts
Enables all 4 cores on boot without PSCI using the dtsi already in the repo.
=> arm64: dts: qcom: apq8016-samsung-gt510wifi: Enable SMP without PSCI

arch/arm64/boot/dts/qcom/apq8016-samsung-gt510wifi.dts
Enable WiFi and BT on this device.
- WiFi: works, but only on 2.4GHz
- BT: pairs, connects, but only briefly (needs more testing)
=> arm64: dts: qcom: apq8016-samsung-gt510wifi: Enable wcnss

arch/arm64/boot/dts/qcom/Makefile, arch/arm64/boot/dts/qcom/msm8916-motorola-harpia.dts
Tested working on my Motorola Moto G4 Play:
=> arm64: dts: qcom: Add device tree for Motorola Moto G4 Play

arch/arm64/boot/dts/qcom/msm8916-motorola-harpia.dts
Confirmed both Wi-Fi and Bluetooth both functional on my Moto G4 Play.
=> arm64: dts: qcom: msm8916-motorola-harpia: Enable WCNSS

arch/arm64/boot/dts/qcom/apq8016-samsung-gt510wifi.dts
Add GPIO keys for:
- Volume Up
- Volume Down
- Home
- Hall (untested)
=> arm64: dts: qcom: apq8016-samsung-gt510wifi: Add GPIO keys

arch/arm64/boot/dts/qcom/apq8016-samsung-gt510wifi.dts
See #45 
Tested since then:
- Microphones
Untested:
- Speaker (supposedly uses an amp, may or may not work by default)
=> gt510wifi: Add audio functionality

arch/arm64/boot/dts/qcom/apq8016-samsung-matissevewifi.dts
[matissevewifi_dmesg.log](https://github.com/msm8916-mainline/linux/files/4302163/matissevewifi_dmesg.log)
=> arm64: dts: qcom: apq8016-samsung-matissevewifi: add WIFI/BT support

arch/arm64/boot/dts/qcom/Makefile, arch/arm64/boot/dts/qcom/msm8916-bq-paella.dts
Added device tree for msm8916t bq-paella
Tested booting without user interface
=> arm64: dts: qcom: Add device tree for BQ Aquaris X5 Cyanogen Edition

arch/arm64/boot/dts/qcom/msm8916-bq-paella.dts
Added WiFi and BlueTooth support
=> arm64: dts: qcom: Add WiFi/BT support for BQ Aquaris X5 Cyanogen Edition

arch/arm64/boot/dts/qcom/Makefile, arch/arm64/boot/dts/qcom/msm8916-samsung-j3ltespr.dts
This enables basic functionality for the Samsung Galaxy J3 2016 (J320P model).
=> arm64: dts: qcom: msm8916-samsung-j3ltespr: Initialize

arch/arm64/boot/dts/qcom/msm8916-bq-paella.dts
Volume buttons tested and working:
```
Event: time 1586628567.175091, type 1 (EV_KEY), code 114 (KEY_VOLUMEDOWN), value 1
Event: time 1586628567.175091, -------------- SYN_REPORT ------------
Event: time 1586628567.289923, type 1 (EV_KEY), code 114 (KEY_VOLUMEDOWN), value 0
Event: time 1586628567.289923, -------------- SYN_REPORT ------------
```
```
Event: time 1586628576.884556, type 1 (EV_KEY), code 115 (KEY_VOLUMEUP), value 1
Event: time 1586628576.884556, -------------- SYN_REPORT ------------
Event: time 1586628577.048528, type 1 (EV_KEY), code 115 (KEY_VOLUMEUP), value 0
Event: time 1586628577.048528, -------------- SYN_REPORT ------------
```
=> arm64: dts: qcom: msm8916-bq-paella: Add volume buttons

arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
need to "apk add linuxconsoletools"
and use "fftest /dev/input/event4"
=> oppo-a51f: add vibration

arch/arm64/boot/dts/qcom/msm8916-bq-paella.dts
Whenever a touch event is available, the touchscreen changes the GPIO
for the IRQ from high -> low (a falling edge). The GPIO is changed back
from low -> high once the touch event has been read with
HX852_READ_ALL_EVENTS.
At least on the BQ models, the touchscreen seems to send an empty
touch event after initial power up, so the GPIO switches to "low".
This is before the IRQ is enabled, so hx852_interrupt() is not triggered.
This means that we don't read the event from the controller
(HX852_READ_ALL_EVENTS) and therefore the GPIO does not change back
from low -> high. This is problematic because hx852_interrupt()
is only triggered when the GPIO switches from high -> low.
It is not triggered when the IRQ stays on low forever.
In other words, we will never get any further touch events from …
=> arm64: dts: qcom: msm8916-bq-paella: Fix touchscreen

arch/arm64/boot/dts/qcom/msm8916-oppo-a51f.dts
after discussion :
seems the earphone & speaker is left channel only, so set it to mono output.
and due to headphone (3.5" phonejack) with ts4621 which is custom PA from oppo, so it's less priority for add it now...
=> oppo-a51f: add sound support 

arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
Every touch at under screen buttons (which are return, home, recent apps in android) leads to` type 1 (EV_KEY), code 330 (BTN_TOUCH), value 1` in evtest. otherwise it works
=> arm64: dts: qcom: msm8916-wingtech-wt86528: add touchscreen

arch/arm64/boot/dts/qcom/msm8916-wingtech-wt86528.dts
elan-epl2182, akm09911 and fan54015 charger are no supported by mainline so imu is the only sensor supported.
=> arm64: dts: qcom: msm8916-wingtech-wt86528: add sensors

arch/arm64/boot/dts/qcom/msm8916-asus-z00l.dts
Device tree for sound. Copied from Motorola Harpia Device tree.
What works,
* Speaker
* Headphone/Earphones
* Primary/Secondary Microphones
* Audio Jack Events.
<strike>What does not work,
When headphone is plugged in, it does not change the output to headphone automatically. Is this a userland problem?(Does the same happen with Motorola Harpia). </strike> (It actually works, It's a userland problem in phosh)
Based the device tree on https://github.com/LineageOS/android_kernel_asus_msm8916/blob/1a45c63742b8c3253a38c2ff97b672918c88d8df/arch/arm/boot/dts/qcom/msm8916-mtp-ze550kl.dtsi#L230
=> arm64: dts: qcom: msm8916-asus-z00l: add sound

sound/soc/codecs/tfa9895.c
This is required on some devices to generate i2c clocks when accessing the amplifier for the first time.
Note:
Comment is based on the comment for msm8996 [here](https://github.com/commaai/android_kernel_comma_msm8996/blob/2bfa5cc327e32051d28236ee18a13debd805186f/drivers/comma/oneplus/sound/tfa98xx.c#L806-L810), I have no idea if it is accurate.. :)
=> ASoC: tfa9895: add dummy read when probing

arch/arm64/boot/dts/qcom/msm8916-asus-z00l.dts
Add support for Gyroscope, Accelerometer and Magnetometer. Downstream device tree reference on these nodes is [here](https://github.com/LineageOS/android_kernel_asus_msm8916/blob/1a45c63742b8c3253a38c2ff97b672918c88d8df/arch/arm/boot/dts/qcom/msm8916-mtp-ze550kl.dtsi#L159).
=> ASUS Zenfone 2 Laser (Z00L) Add Sensors

arch/arm64/boot/dts/qcom/Makefile, arch/arm64/boot/dts/qcom/msm8916-alcatel-alto5-vdf.dts
Add initial device tree for Alcatel Alto 5 VDF, which appears to be the same device as Vodafone Smart Prime 6 (VF-895N). This device tree has been tested on a Vodafone Smart Prime 6 (VF-895N).
=> arm64: dts: qcom: msm8916-alcatel-alto5-vdf: Add initial device tree

Documentation/devicetree/bindings/sound/nxp,tfa989x.yaml, arch/arm64/boot/dts/qcom/msm8916-alcatel-idol347.dts, sound/soc/codecs/tfa989x.c
* (Quoting @Minecrell ) For the RCV my idea was to argue that some TFA* have some RCV register bit.
So in a way you would add support to use this "rcv" register bit, but add an alternative implementation using a gpio.
like, it's functionality that exists in TFA, and you just optionally add something to trigger a gpio when rcv is used
=> Add tfa9897 support in new tfa989x driver

arch/arm64/boot/dts/qcom/apq8016-samsung-gt510wifi.dts, arch/arm64/boot/dts/qcom/apq8016-samsung-matissevewifi.dts
There was some upstream change recently where `reset-gpios` for atmel mxt should now be `GPIO_ACTIVE_LOW` instead of `GPIO_ACTIVE_HIGH`. This broke the touchscreen on gt510wifi (and probably matissevewifi). Also, the regulators can now be specified correctly.
Reported and tested by Luis on gt510wifi, so I'm just guessing matissevewifi works better with these changes as well.
Cc: @jja2000 @rvlander
=> samsung-gt510wifi/matissevewifi: Fix touchscreen

arch/arm64/boot/dts/qcom/msm8916.dtsi, drivers/net/ethernet/qualcomm/bam-dmux.c
These changes are required to make the bam-dmux driver work with the changes that landed in upstream ModemManager. It was decided that it is cleaner to have it use Raw-IP mode rather than Ethernet mode (which is somewhat broken).
I'm looking for some testing here to make sure that it does not break anything, although I was not able to notice any problems on bq-paella. See https://gitlab.com/postmarketOS/pmaports/-/merge_requests/1966.
=> net: qualcomm: bam-dmux: Switch to Raw IP mode and other cleanups

arch/arm64/boot/dts/qcom/Makefile, arch/arm64/boot/dts/qcom/msm8916-lg-c50.dts
I can confirm that eMMC, USB, WiFi/BT, gpio-keys work, but MicroSD does not work (SDHCI is initialized, but SD card is not) with "typical" binding even without cd gpio, basically:
```
&sdhc_2 {
status = "okay";
pinctrl-names = "default", "sleep";
pinctrl-0 = <&sdc2_clk_on &sdc2_cmd_on &sdc2_data_on>;
pinctrl-1 = <&sdc2_clk_off &sdc2_cmd_off &sdc2_data_off>;
non-removable;
};
```
The one difference i found between other devices is that downstream does not have vmmc (downstream vdd) supply. Probably lg-c50 uses some another supply which is enabled by another hardware. Any suggestions? I attached decompiled downstream device-tree and dmesg with enabled SD card node.
[dmesg_c50.txt](https://github.com/msm8916-mainline/linux/files/6226067/dmesg_c50.txt) …
=> arm64: dts: qcom: msm8916-lg-c50: add initial device-tree for LG Leon LTE

arch/arm64/boot/dts/qcom/apq8016-samsung-gtelwifiue.dts, drivers/gpu/drm/panel/msm8916-generated/Makefile, drivers/gpu/drm/panel/msm8916-generated/panel-samsung-nt51017-b4p096wx5vp09.c
Adds the generated panel driver for the device, and adds it to the
dtb, along with support for the ZT7554 touchscreen. The touchscreen
works fine, along with the panel.
Signed-off-by: Michael Abood <person4265@gmail.com>
=> arm64: dts: qcom: samsung-gtelwifiue: Add panel and touchscreen

arch/arm64/boot/dts/qcom/Makefile, arch/arm64/boot/dts/qcom/msm8916-samsung-a5-zt.dts
Samsung Galaxy A5 (SM-A500YZ) is a smartphone using the MSM8916 SoC released
in 2015.
The A5 variants are very similar, with some differences in accelerometer and
touch key. The common parts are shared in msm8916-samsung-a5u-eur.dts to reduce
duplication.
The difference of accelerometer between A5U/A5ZT is the way the sensor is
mounted on the mainboard - set the mount-matrix in the
device-specific device tree part to handle that difference.
On A5ZT the touch key is supplied by a single fixed
regulator (enabled via GPIO 60) that supplies both MCU and LED.
A5ZT doesn't have an NFC chip.
=> arm64: dts: qcom: msm8916-samsung-a5-zt: Add initial device tree

arch/arm/boot/dts/Makefile, arch/arm/boot/dts/qcom-msm8916-samsung-heatqlte.dts, arch/arm64/boot/dts/qcom/Makefile, arch/arm64/boot/dts/qcom/msm8916-samsung-cprime-common.dtsi, arch/arm64/boot/dts/qcom/msm8916-samsung-cprime.dts, arch/arm64/boot/dts/qcom/msm8916-samsung-fortunaltezt.dts, arch/arm64/boot/dts/qcom/msm8916-samsung-gprime-common.dtsi, arch/arm64/boot/dts/qcom/msm8916-samsung-heatqlte.dts, drivers/gpu/drm/panel/msm8916-generated/Makefile, drivers/gpu/drm/panel/msm8916-generated/panel-samsung-s6288a0.c, drivers/gpu/drm/panel/msm8916-generated/panel-samsung-sc7798a-bv045wvm.c
Samsung Galaxy Ace 4 and Core Prime are phones based on MSM8916. They are
similar to the other Samsung devices based on MSM8916 with only a few
minor differences.
The device tree contains initial support for Ace 4 and Core Prime with:
- GPIO keys
- SDHCI (internal and external storage)
- USB Device Mode (on USB connector via the SM5504 MUIC)
- UART
- WCNSS (WiFi/BT)
- Regulators
- Vibration motor
- Sound and Modem
- Accelerometer
- NFC
Ace 4, Core Prime and Grand Prime are similar, with some differences in
MUIC, panel and touchscreen. The common parts are
shared in `msm8916-samsung-cprime-common.dtsi`
and `msm8916-samsung-gprime-common.dtsi` to reduce duplication.
Cc @eloydegen @garethppls
=> arm64: dts: qcom: msm8916-samsung-{cprime,heatqlte}: Add initial device tree
